### PR TITLE
clean up `dcos package search --json` response

### PR DESCRIPTION
**Pull request by tamarrow**
removed superfluous outer list of packages 
```json
{
  "packages": [
    {
      "currentVersion": "0.2.0-1",
      "description": "Apache Cassandra running on Apache Mesos",
      "framework": true,
      "name": "cassandra",
      "tags": [
        "data",
        "database",
        "nosql"
      ],
      "versions": {
        "0.2.0-1": "0"
      }
    }
  ]
}
```

### CODE REVIEW

**Comment by tamarrow** [comment]
cc @BenWhitehead

**Comment by BenWhitehead** [comment]
:ship: it when green

**Comment by jsancio** [comment]
Fixes #488

**Comment by jsancio** [comment]
:sunglasses: LGTM.

**Pull request merged**
