### PR TITLE
PROTOTYPE: pyinstaller support

### PR DESCRIPTION
**Pull request by sttts**
```
$ make pyinstaller
$ dist/dcos
Command line utility for the Mesosphere Datacenter Operating
System (DCOS). The Mesosphere DCOS is a distributed operating
system built around Apache Mesos. This utility provides tools
for easy management of a DCOS installation.

Available DCOS commands:

	cassandra      	Communicate with Cassandra-Mesos REST API in DCOS cluster
	config         	Get and set DCOS CLI configuration properties
	hdfs           	Utilities for building and managing your HDFS installation
	help           	Display command line usage information
	kubectl        	Deploy and manage pods on Kubernetes
	kubernetes     	Deploy and manage pods on Kubernetes
	marathon       	Deploy and manage applications on the DCOS
	node           	Manage DCOS nodes
	package        	Install and manage DCOS packages
	service        	Manage DCOS services
	spark          	Run and manage Spark jobs
	task           	Manage DCOS tasks

Get detailed command description with 'dcos <command> --help'.
$ dist/dcos kubectl
Download kubectl from http://pool-4e16-elasticl-1xewf4jjmnouz-518730075.us-west-2.elb.amazonaws.com/service/kubernetes/static/darwin/kubectl.bz2
kubectl controls the Kubernetes cluster manager.

Find more information at https://github.com/kubernetes/kubernetes.

Usage:
  kubectl [flags]
  kubectl [command]

Available Commands:
  get            Display one or many resources
  describe       Show details of a specific resource or group of resources
  create         Create a resource by filename or stdin
  replace        Replace a resource by filename or stdin.
  patch          Update field(s) of a resource by stdin.
  delete         Delete resources by filenames, stdin, resources and names, or by resources and label selector.
  edit           Edit a resource on the server
  apply          Apply a configuration to a resource by filename or stdin
  namespace      SUPERSEDED: Set and view the current Kubernetes namespace
  logs           Print the logs for a container in a pod.
  rolling-update Perform a rolling update of the given ReplicationController.
  scale          Set a new size for a Replication Controller.
  attach         Attach to a running container.
  exec           Execute a command in a container.
  port-forward   Forward one or more local ports to a pod.
  proxy          Run a proxy to the Kubernetes API server
  run            Run a particular image on the cluster.
  stop           Deprecated: Gracefully shut down a resource by name or filename.
  expose         Take a replication controller, service or pod and expose it as a new Kubernetes Service
  autoscale      Auto-scale a replication controller
  label          Update the labels on a resource
  annotate       Update the annotations on a resource
  config         config modifies kubeconfig files
  cluster-info   Display cluster info
  api-versions   Print the supported API versions on the server, in the form of "group/version".
  version        Print the client and server version information.
  help           Help about any command

Flags:
      --alsologtostderr[=false]: log to standard error as well as files
      --api-version="": The API version to use when talking to the server
      --certificate-authority="": Path to a cert. file for the certificate authority.
      --client-certificate="": Path to a client key file for TLS.
      --client-key="": Path to a client key file for TLS.
      --cluster="": The name of the kubeconfig cluster to use
      --context="": The name of the kubeconfig context to use
      --insecure-skip-tls-verify[=false]: If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure.
      --kubeconfig="": Path to the kubeconfig file to use for CLI requests.
      --log-backtrace-at=:0: when logging hits line file:N, emit a stack trace
      --log-dir="": If non-empty, write log files in this directory
      --log-flush-frequency=5s: Maximum number of seconds between log flushes
      --logtostderr[=true]: log to standard error instead of files
      --match-server-version[=false]: Require server version to match client version
      --namespace="": If present, the namespace scope for this CLI request.
      --password="": Password for basic authentication to the API server.
  -s, --server="": The address and port of the Kubernetes API server
      --stderrthreshold=2: logs at or above this threshold go to stderr
      --token="": Bearer token for authentication to the API server.
      --user="": The name of the kubeconfig user to use
      --username="": Username for basic authentication to the API server.
      --v=0: log level for V logs
      --vmodule=: comma-separated list of pattern=N settings for file-filtered logging


Use "kubectl [command] --help" for more information about a command.
$ ls -l dist
total 118968
-rwxr-xr-x  1 sts  staff  7509232 12 Dez 19:16 dcos
-rwxr-xr-x  1 sts  staff  7506709 12 Dez 19:16 dcos-config
-rwxr-xr-x  1 sts  staff  7505263 12 Dez 19:16 dcos-help
-rwxr-xr-x  1 sts  staff  7568035 12 Dez 19:16 dcos-marathon
-rwxr-xr-x  1 sts  staff  7557660 12 Dez 19:16 dcos-node
-rwxr-xr-x  1 sts  staff  7845160 12 Dez 19:17 dcos-package
-rwxr-xr-x  1 sts  staff  7843669 12 Dez 19:17 dcos-service
-rwxr-xr-x  1 sts  staff  7557650 12 Dez 19:17 dcos-task
```

### CODE REVIEW

**Comment by guenter** [comment]
This is great @sttts! Removes so many sources of errors.

**Comment by jsancio** [comment]
@sttts I'll play around with this today! I am really excited for this PR!

**Comment by jsancio** [comment]
@sttts I merged from master to kick a build of this PR.

**Comment by jsancio** [comment]
Closing after merging #542 .

**Pull request closed without merging**
