### PR TITLE
[ADD] DCOS-646 Add --colors flag to force JSON syntax highlighting.

### PR DESCRIPTION
**Pull request by YuraTolochkevich**

### CODE REVIEW

**Comment by tamarrow** [comment]
shouldn't we only allow this if the user also specifies `--json`?

**Comment by YuraTolochkevich** [comment]
@tamarrow yes, we should only allow  --colors only with --json.  PR is updated

**Comment by ssk2** [comment]
@YuraTolochkevich - apologies for the delay. We discussed this flag and decided that we should avoid adding `--colors`. Instead, we should only print colors if this is printing to a TTY or sending to the default pager. If the pager environment variable has been overwrriten or we are not printing to a TTY, we just won't bother with color. 

It looks like this might be the behaviour already - can you confirm this? Apologies for the wasted effort - we had some confusion over what was needed (this is an old ticket!).

**Comment by YuraTolochkevich** [comment]
right, this behavior  is implemented already. Let me to discard this PR?

**Comment by ssk2** [comment]
@YuraTolochkevich - yes, let's close it. Again apologies!

**Pull request closed without merging**
