### PR TITLE
Provide opt-out install script

### PR DESCRIPTION
**Pull request by jsancio**
Don't merge yet as I am testing this manually but you can start the review. I changed/added lines 112-113. cc @pyronicide

### CODE REVIEW

**Comment by jsancio** [comment]
@tamarrow @pyronicide It works. Ready for review.

**Comment by tamarrow** [comment]
@jsancio can we have a shared file of common code for the two installers? should we add a test for this?

**Comment by pyronicide** [comment]
@tamarrow This is one-off and we should probably rewrite the installers in the future. I'm not sure it is worth the effort of refactoring/testing.

**Comment by jsancio** [comment]
re-running tests.

**Pull request merged**
