### PR TITLE
[DCOS-2402] Prints the ssh command used in `dcos node ssh` and `dcos service log

### PR DESCRIPTION
**Pull request by mgummelt**
marathon` to help the user debug SSH issues

### CODE REVIEW

**Comment by mgummelt** [comment]
Note I don't know how to test this because for some weird reason I can't get the stderr output from the subprocess.  `stderr.read()` always returns an empty string.  It has something to do with attaching `stdin` to the pty.

**Comment by mgummelt** [comment]
@jsancio: tests passing

**Comment by jsancio** [comment]
> Note I don't know how to test this because for some weird reason I can't get the stderr output from the subprocess. stderr.read() always returns an empty string. It has something to do with attaching stdin to the pty.

Can you point me to test that would need fixing? Maybe an extra pair of eyes can figure out what is wrong.

**Comment by jsancio** [comment]
LGTM.

**Pull request merged**
