### PR TITLE
Attempts to use virtualenv 3.4

### PR DESCRIPTION
**Pull request by massenz**

### CODE REVIEW

**Comment by mgummelt** [comment]
@tamarrow can you resolve this?

**Comment by tamarrow** [comment]
recent tests show this is not l

**Comment by tamarrow** [comment]
recent test showed this is no longer an issue. @massenz is doing one more test and then will close if all is still good

**Comment by massenz** [comment]
Tested in a reasonably clean Ubuntu 14.04 box (OpenStack controller stack installed).
This did *not* have `virtualenv` or `pip` previously installed
```
$ which virtualen
$ wget https://bootstrap.pypa.io/get-pip.py
$ sudo python get-pip.py 
$ which pip
/usr/local/bin/pip
$ sudo -H pip install virtualenv
...  
Downloading virtualenv-13.1.0-py2.py3-none-any.whl (1.7MB)
...
Successfully installed virtualenv-13.1.0
$ virtualenv --version
13.1.0
```
so this should work on a clean installation;
```
sudo -H pip install --upgrade virtualenv
```
should work on an existing install with an older version of `virtualenv`

**Pull request closed without merging**
