### PR TITLE
dcos-2313 don't crash if schema not correctly formatted

### PR DESCRIPTION
**Pull request by tamarrow**

### CODE REVIEW

**Comment by jsancio** [comment]
Thanks! I think we need some tests that exercise the failure case. Probably easiest to write unittest for  the function `_extract_default_values`.

**Comment by tamarrow** [comment]
@jsancio added tests

**Comment by jsancio** [comment]
Let's use `pytest.fixture` to inject test cases. Checkout https://github.com/mesosphere/dcos-cli/blob/master/tests/test_package.py#L12-L35 and https://github.com/mesosphere/dcos-cli/blob/master/tests/test_package.py#L76-L79

**Comment by tamarrow** [comment]
Didn't we decide to no longer use `pytest.fixture`?

**Comment by jsancio** [comment]
> Didn't we decide to no longer use pytest.fixture?

I was referring to using it to teardown and setup modules. I think they are still useful for injecting test cases.

**Comment by tamarrow** [comment]
@jsancio updated

**Comment by jsancio** [comment]
Very nice! LGTM. Will :shipit: when CI passes.

**Pull request merged**
