### PR TITLE
Add bash completion for all dcos cli commands

### PR DESCRIPTION
**Pull request by hayderimran7**
Bash auto completion added for Linux/Darwin based systems,
where the script will be added automatically upon installing the
cli package. All commands for autocompletion added with the help
of :
https://docs.mesosphere.com/using/cli/

### CODE REVIEW

**Comment by ssk2** [comment]
@hayderimran7 - awesome, we've been wanting this for a while :).

**Comment by ssk2** [comment]
You've got a typo in the name of your script `dcos.bash_comletion`-> `dcos.bash_completion`.

**Comment by jsancio** [comment]
@hayderimran7 Thanks for submitting this PR!

We have been looking to implement autocomplete for a while now. The DCOS CLI uses (docopt)[https://github.com/docopt/docopt] to parse the command line specification at https://github.com/mesosphere/dcos-cli/tree/master/cli/dcoscli/data/help and in the `main.py` files in https://github.com/mesosphere/dcos-cli/tree/master/cli/dcoscli
and its sub-directory. Have you thought about implementing this by using the docopt parser to generate the AST? We should be able to use this AST to implement auto-completion.

I am concerned that with this implementation we are going to have multiple hard states that need to get updated when we make change to a command.

Also, the CLI supports extension by dynamically adding and discovering subcommands. Ideally, our autocomplete implementation would support that mechanism for adding subcommand and autocompletion for them.

Thanks!

**Comment by hayderimran7** [comment]
@jsancio  thank you - i have to agree with  you on the flexibility of going this way, i myself have implemented the autocompletion on openstack projects using module inspection and adding those member functions dynamically to the data that needs to be autocompleted. 
so thanks for linking me to docopt, I will investigate more on it and try to come up with better solution :)

**Comment by jsancio** [comment]
Thank you @hayderimran7. I am going to close this PR for now. Please submit another PR after your investigation. Looking forward to the new PR!

**Pull request closed without merging**
